FROM gradle:8.7-jdk17 AS build
WORKDIR /app

COPY gradle gradle
COPY build.gradle settings.gradle gradlew ./

RUN ./gradlew --no-daemon dependencies || true

COPY src src

RUN ./gradlew --no-daemon clean bootJar

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080
ENV JAVA_OPTS=""

# Run
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]